INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE', NOW());
INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE', NOW());
INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE', NOW());

INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE', NOW());
INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE', NOW());
INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE', NOW());

INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE', NOW());
INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE',NOW());
INSERT INTO PRODUCT ( PRICE , STATUS, LAST_MODIFIED_DATE  ) VALUES ( 40, 'AVAILABLE' ,NOW());


